### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by micro-jumbo** [devleaks/yii2-metafizzy#1]
When trying to run

```
composer require --prefer-dist devleaks/yii2-metafizzy "*"
```

I get 

> The requested package devleaks/yii2-metafizzy could not be found in any version, there may be a typo in the package name.

When changed to 

```
composer require --prefer-dist devleaks/yii2-metafizzy "*@dev"
```

it installs, but with old dependencies, for instance isotope in version 1.5.26, which has different directories layout and file names than those defined in AssetBundles. Because of that it's completely unusable.

**Comment by devleaks** [comment]
Hello,

Sorry about this, but I can't do much. Somebody else entered this package on packagist and the packagist entry points to an earlier release. I cannot update the packagist entry since I don't own it.
The work around is to bypass packagist and force the repository in your composer.son file:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/devleaks/yii2-metafizzy"
        }
    ],
```

That way, to my understanding, composer will not lookup the package definition at packagist, but directly on github. (I'm a victim of this: https://github.com/composer/packagist/issues/346)

**Comment by micro-jumbo** [comment]
There is also another problem - `isotope` depends on `outlayer`, which depends on `eventEmitter`. There is an issue with case (in)sensitivity between composer and bower (https://github.com/francoispluchino/composer-asset-plugin/issues/70). As a result composer is downloading `eventemitter`, where it should download `eventEmitter`. As a workaround one should add asset-repository in his application `composer.json`:

``` json
    "extra": {
        "asset-repositories": [
            {
                "name": "bower-asset/eventemitter",
                "type": "bower-vcs",
                "url": "git://github.com/Olical/EventEmitter.git"
            }
        ]
    },
```

**Comment by devleaks** [comment]
Thank you.
